# Generated by Django 4.2.3 on 2023-07-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snacks',
            old_name='reviewer',
            new_name='purchaser',
        ),
        migrations.AddField(
            model_name='snacks',
            name='description',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
